import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author empress
 */
public class Form extends javax.swing.JFrame {
    Connection conn;
    Statement state;
    ResultSet Rset;
    int curRow;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        DoConnect();
    }
    public void DoConnect( ) {
       try{
            String host = "jdbc:derby://localhost:1527/EttiJobServ";
            String dName = "administrator";
            String dPass = "admin";
            conn = DriverManager.getConnection( host, dName, dPass ); //Connect to database and extract records
            state = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String SQL = "select * from ADMINISTRATOR.\"Studenti\"";
            Rset = state.executeQuery( SQL );
            
            Rset.next();
            String sNume = Rset.getString("Nume");
            String sPrenume = Rset.getString("Prenume");
            String sStudii = Rset.getString("Studii");
            String sSpecializare = Rset.getString("Specializare");
            String sAn= Rset.getString("An");
            String sCompanie = Rset.getString("Companie");
            String sDomeniu = Rset.getString("Domeniu");
            String sPozitie = Rset.getString("Pozitie");

            txtNume.setText(sNume);
            txtPrenume.setText(sPrenume);
            txtStudii.setText(sStudii);
            txtSpecializare.setText(sSpecializare);
            txtAn.setText(sAn);
            txtCompanie.setText(sCompanie);
            txtDomeniu.setText(sDomeniu);
            txtPozitie.setText(sPozitie);
       }
        catch ( SQLException err ) { //Handle database connection errors
             System.out.println( err.getMessage( ) );
       }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Specializare = new javax.swing.JPanel();
        lblNume = new javax.swing.JLabel();
        lblPrenume = new javax.swing.JLabel();
        lblStudii = new javax.swing.JLabel();
        lblSpecializare = new javax.swing.JLabel();
        lblAn = new javax.swing.JLabel();
        lblCompanie = new javax.swing.JLabel();
        lblDomeniu = new javax.swing.JLabel();
        lblPozitie = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        txtPrenume = new javax.swing.JTextField();
        txtStudii = new javax.swing.JTextField();
        txtAn = new javax.swing.JTextField();
        txtCompanie = new javax.swing.JTextField();
        txtDomeniu = new javax.swing.JTextField();
        txtPozitie = new javax.swing.JTextField();
        txtSpecializare = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Specializare.setBackground(new java.awt.Color(207, 253, 253));

        lblNume.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNume.setText("Nume");

        lblPrenume.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrenume.setText("Prenume");

        lblStudii.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStudii.setText("Studii");

        lblSpecializare.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSpecializare.setText("Specializare");

        lblAn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAn.setText("An");

        lblCompanie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanie.setText("Companie");

        lblDomeniu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDomeniu.setText("Domeniu");

        lblPozitie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPozitie.setText("Pozitie");

        txtNume.setText(" ");

        txtAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SpecializareLayout = new javax.swing.GroupLayout(Specializare);
        Specializare.setLayout(SpecializareLayout);
        SpecializareLayout.setHorizontalGroup(
            SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecializareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addComponent(lblSpecializare)
                        .addGap(15, 15, 15)
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAn, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtSpecializare))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAn)
                            .addComponent(lblNume)
                            .addComponent(lblPrenume)
                            .addComponent(lblStudii))
                        .addGap(27, 27, 27)
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrenume, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudii)
                            .addComponent(txtNume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(95, 95, 95)))
                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCompanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDomeniu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPozitie))
                .addGap(34, 34, 34)
                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDomeniu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPozitie)
                    .addComponent(txtCompanie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        SpecializareLayout.setVerticalGroup(
            SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecializareLayout.createSequentialGroup()
                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNume)
                            .addComponent(txtCompanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompanie)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SpecializareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SpecializareLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrenume)
                                    .addComponent(txtPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SpecializareLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDomeniu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDomeniu))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPozitie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPozitie)))
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudii))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpecializare)
                            .addComponent(txtSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(SpecializareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblAn))
                    .addGroup(SpecializareLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Informatii Studenti");

        btnFirst.setText("Primul");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setText("Anterior");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Urmatorul");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText("Utimul");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnAdd.setText("Adauga");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Sterge");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Salveaza");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Actualizeaza");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Anuleaza");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Specializare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(Specializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFirst)
                        .addComponent(btnPrevious)
                        .addComponent(btnNext)
                        .addComponent(btnLast)
                        .addComponent(btnAdd)
                        .addComponent(btnDelete)
                        .addComponent(btnSave)
                        .addComponent(btnUpdate)
                        .addComponent(btnCancel)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
//        btnFirst.setEnabled( false );
//        btnPrevious.setEnabled( false ) ;
//        btnNext.setEnabled( false );
//        btnLast.setEnabled( false );
//        btnUpdate.setEnabled( false );
//        btnDelete.setEnabled( false );
//        btnAdd.setEnabled( false );
//        btnSave.setEnabled( true );
//        btnCancel.setEnabled( true );
        try {
            Rset.first();
            String sNume = Rset.getString("Nume");
            String sPrenume = Rset.getString("Prenume");
            String sStudii = Rset.getString("Studii");
            String sSpecializare = Rset.getString("Specializare");
            String sAn= Rset.getString("An");
            String sCompanie = Rset.getString("Companie");
            String sDomeniu = Rset.getString("Domeniu");
            String sPozitie = Rset.getString("Pozitie");

            txtNume.setText(sNume);
            txtPrenume.setText(sPrenume);
            txtStudii.setText(sStudii);
            txtSpecializare.setText(sSpecializare);
            txtAn.setText(sAn);
            txtCompanie.setText(sCompanie);
            txtDomeniu.setText(sDomeniu);
            txtPozitie.setText(sPozitie);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }

    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            if ( Rset.next()) {
                String sNume = Rset.getString("Nume");
                String sPrenume = Rset.getString("Prenume");
                String sStudii = Rset.getString("Studii");
                String sSpecializare = Rset.getString("Specializare");
                String sAn= Rset.getString("An");
                String sCompanie = Rset.getString("Companie");
                String sDomeniu = Rset.getString("Domeniu");
                String sPozitie = Rset.getString("Pozitie");

                txtNume.setText(sNume);
                txtPrenume.setText(sPrenume);
                txtStudii.setText(sStudii);
                txtSpecializare.setText(sSpecializare);
                txtAn.setText(sAn);
                txtCompanie.setText(sCompanie);
                txtDomeniu.setText(sDomeniu);
                txtPozitie.setText(sPozitie);
            }
            else {
                Rset.previous( );
                JOptionPane.showMessageDialog(this, "End of File");
            }
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            Rset.last();
            String sNume = Rset.getString("Nume");
            String sPrenume = Rset.getString("Prenume");
            String sStudii = Rset.getString("Studii");
            String sSpecializare = Rset.getString("Specializare");
            String sAn= Rset.getString("An");
            String sCompanie = Rset.getString("Companie");
            String sDomeniu = Rset.getString("Domeniu");
            String sPozitie = Rset.getString("Pozitie");

            txtNume.setText(sNume);
            txtPrenume.setText(sPrenume);
            txtStudii.setText(sStudii);
            txtSpecializare.setText(sSpecializare);
            txtAn.setText(sAn);
            txtCompanie.setText(sCompanie);
            txtDomeniu.setText(sDomeniu);
            txtPozitie.setText(sPozitie);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        try {
            if ( Rset.previous()) {
                String sNume = Rset.getString("Nume");
                String sPrenume = Rset.getString("Prenume");
                String sStudii = Rset.getString("Studii");
                String sSpecializare = Rset.getString("Specializare");
                String sAn= Rset.getString("An");
                String sCompanie = Rset.getString("Companie");
                String sDomeniu = Rset.getString("Domeniu");
                String sPozitie = Rset.getString("Pozitie");

                txtNume.setText(sNume);
                txtPrenume.setText(sPrenume);
                txtStudii.setText(sStudii);
                txtSpecializare.setText(sSpecializare);
                txtAn.setText(sAn);
                txtCompanie.setText(sCompanie);
                txtDomeniu.setText(sDomeniu);
                txtPozitie.setText(sPozitie);
            }
            else {
                Rset.next( );
                JOptionPane.showMessageDialog(this, "End of File");
            }}
            catch (SQLException err) {
                JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
            
        try {
            String upNume = Rset.getString("Nume");
            String upPrenume = Rset.getString("Prenume");
            String upStudii = Rset.getString("Studii");
            String upSpecializare = Rset.getString("Specializare");
            String upAn= Rset.getString("An");
            String upCompanie = Rset.getString("Companie");
            String upDomeniu = Rset.getString("Domeniu");
            String upPozitie = Rset.getString("Pozitie");
        
            Rset.updateString("Nume", upNume);
            Rset.updateString("Prenume", upPrenume);
            Rset.updateString("Studii", upStudii);
            Rset.updateString("Specializare", upSpecializare);
            Rset.updateString("An", upAn);
            Rset.updateString("Companie", upCompanie);
            Rset.updateString("Domeniu", upDomeniu);
            Rset.updateString("Pozitie", upPozitie);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            curRow = Rset.getRow( ); 
            Rset.last( ); 
            txtNume.setText("");
            txtPrenume.setText("");
            txtStudii.setText("");
            txtSpecializare.setText("");
            txtAn.setText("");
            txtCompanie.setText("");
            txtDomeniu.setText("");
            txtPozitie.setText("");
            
            btnFirst.setEnabled( false );
            btnPrevious.setEnabled( false ) ;
            btnNext.setEnabled( false );
            btnLast.setEnabled( false );
            btnUpdate.setEnabled( false );
            btnDelete.setEnabled( false );
            btnAdd.setEnabled( false );
            btnSave.setEnabled( true );
            btnCancel.setEnabled( true );
        }
            catch (SQLException err) {
                JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            Rset.absolute( curRow ); 
            txtNume.setText( Rset.getString("Nume") );
            txtPrenume.setText(Rset.getString("Prenume"));
            txtStudii.setText(Rset.getString("Studii"));
            txtSpecializare.setText(Rset.getString("Specializare"));
            txtAn.setText(Rset.getString("An"));
            txtCompanie.setText(Rset.getString("Companie"));
            txtDomeniu.setText(Rset.getString("Domeniu"));
            txtPozitie.setText(Rset.getString("Pozitie"));
            
            btnFirst.setEnabled( true );
            btnPrevious.setEnabled( true ) ;
            btnNext.setEnabled( true );
            btnLast.setEnabled( true );
            btnUpdate.setEnabled( true );
            btnDelete.setEnabled( true );
            btnAdd.setEnabled( true );
            btnSave.setEnabled( false );
            btnCancel.setEnabled( false );
        }
            catch (SQLException err) {
                JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Get data from form text fields
        String newNume = txtNume.getText();
        String newPrenume = txtPrenume.getText();
        String newStudii = txtStudii.getText();
        String newSpecializare = txtSpecializare.getText();
        String newAn= txtAn.getText();
        String newCompanie = txtCompanie.getText();
        String newDomeniu = txtDomeniu.getText();
        String newPozitie = txtPozitie.getText();
 
    //Check if user has entered required data
    if(newNume.equals("")||newPrenume.equals("")||newStudii.equals("")||newSpecializare.equals("")
        ||newAn.equals("")||newCompanie.equals("")||newDomeniu.equals("")|| newPozitie.equals("") ){
        JOptionPane.showMessageDialog(this, "Introduceti toate datele!");
    }
    else{
        try {
        //Update ResultSet with new data
        Rset.moveToInsertRow( );
        Rset.updateString( "Nume", newNume );
        Rset.updateString( "Prenume", newPrenume );
        Rset.updateString( "Studii", newStudii );
        Rset.updateString( "Specializare", newSpecializare );
        Rset.updateString( "An", newAn );
        Rset.updateString( "Companie", newCompanie );
        Rset.updateString( "Domeniu", newDomeniu);
        Rset.updateString( "Pozitie", newPozitie);
     
     
        Rset.insertRow( ); //Insert row into table
        Rset.close( ); //Close ResultSet
        state.close( ); //Close connection 
     
        //Re-load table data
        state = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String SQL = "select * from ADMINISTRATOR.\"Studenti\"";
        Rset = state.executeQuery( SQL );
        
        Rset.last( ); //Got to last record and get data
        String sNume = Rset.getString("Nume");
        String sPrenume = Rset.getString("Prenume");
        String sStudii = Rset.getString("Studii");
        String sSpecializare = Rset.getString("Specializare");
        String sAn= Rset.getString("An");
        String sCompanie = Rset.getString("Companie");
        String sDomeniu = Rset.getString("Domeniu");
        String sPozitie = Rset.getString("Pozitie");
         
        //Populate form with data again
        txtNume.setText(sNume);
        txtPrenume.setText(sPrenume);
        txtStudii.setText(sStudii);
        txtSpecializare.setText(sSpecializare);
        txtAn.setText(sAn);
        txtCompanie.setText(sCompanie);
        txtDomeniu.setText(sDomeniu);
        txtPozitie.setText(sPozitie);
     
        //Disable/Enable appropriate buttons
        btnFirst.setEnabled( true );
        btnPrevious.setEnabled( true ) ;
        btnNext.setEnabled( true );
        btnLast.setEnabled( true );
        btnUpdate.setEnabled( true );
        btnDelete.setEnabled( true );
        btnAdd.setEnabled( true );
        btnSave.setEnabled( false );
        btnCancel.setEnabled( false );
 
        JOptionPane.showMessageDialog(this, "Record saved successfully");
        }
        catch (SQLException err) { //Handle errors here
            JOptionPane.showMessageDialog(this, err.getMessage( ));
        }
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //Ask user to confirm record deletion
        int temp = JOptionPane.showConfirmDialog(null, "Doriti sa stergeti inregistrarea?" , "Confirmati stergerea" , JOptionPane.YES_NO_OPTION);
        if (temp == 0) //Here we check which option was selected by user: Yes = 0
        {
          try {
              Rset.deleteRow( ); //Delete table record
              Rset.close( ); //Close ResultSet
              state.close( ); //Close connection 

              //Re-load table data
              state = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
              String SQL = "select * from ADMINISTRATOR.\"Studenti\"";
              Rset = state.executeQuery( SQL );

              Rset.next( );
              String sNume = Rset.getString("Nume");
              String sPrenume = Rset.getString("Prenume");
              String sStudii = Rset.getString("Studii");
              String sSpecializare = Rset.getString("Specializare");
              String sAn= Rset.getString("An");
              String sCompanie = Rset.getString("Companie");
              String sDomeniu = Rset.getString("Domeniu");
              String sPozitie = Rset.getString("Pozitie");

              //Populate form with data again
              txtNume.setText(sNume);
              txtPrenume.setText(sPrenume);
              txtStudii.setText(sStudii);
              txtSpecializare.setText(sSpecializare);
              txtAn.setText(sAn);
              txtCompanie.setText(sCompanie);
              txtDomeniu.setText(sDomeniu);
              txtPozitie.setText(sPozitie);
              JOptionPane.showMessageDialog(this, "Stergerea a avut loc cu succes.");
              }
          catch (SQLException err) { //Handle errors here
              JOptionPane.showMessageDialog(this, err.getMessage());
              }
           }
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Specializare;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAn;
    private javax.swing.JLabel lblCompanie;
    private javax.swing.JLabel lblDomeniu;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblPozitie;
    private javax.swing.JLabel lblPrenume;
    private javax.swing.JLabel lblSpecializare;
    private javax.swing.JLabel lblStudii;
    private javax.swing.JTextField txtAn;
    private javax.swing.JTextField txtCompanie;
    private javax.swing.JTextField txtDomeniu;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtPozitie;
    private javax.swing.JTextField txtPrenume;
    private javax.swing.JTextField txtSpecializare;
    private javax.swing.JTextField txtStudii;
    // End of variables declaration//GEN-END:variables
}
